[package]
name = "lucasx150/checkout"
description = "DevProduct and Gamepass grant handling"
version = "0.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["dev.project.json"]

[dependencies]
